version: '3.6'

#
# Run this integration test by running:
# ID=$(docker build -q .) && LOCAL_IMAGE_ID=$ID docker-compose -f docker-compose-integration-tests.yml up --abort-on-container-exit --always-recreate-deps
#
# docker images | grep kth-azure-app_app | awk '{ print $3 }' | xargs docker inspect | grep se.kth.imageVersion
services:

  #############################################
  # Start http://api:80/
  #############################################
  api:
    image: $LOCAL_IMAGE_ID
    ports:
      - 80

  #############################################
  # Start the client running tests agains http://api:80/
  #############################################
  integration-tests:
    # Build client image and run tests from inside that.
    build: ./tests/integration-tests
    depends_on:
      - api
